### ISSUE TITLE
[EPIC] Notification system

### ISSUE THREAD

**Issue by triszt4n** [triszt4n/remark#79]
- [x] SignalR
- [x] Message queue with Service Bus
- [x] Azure Functions working in the background
- [x] Frontend for receiving
- [x] Button in UI for notification menu
- [x] Complete all CRUD functions to create messages to message queue

**Comment by triszt4n** [comment]
Események, amikre már van notification készítés:
* Moderátorként lettél hozzáadva egy csatornához
  * in: channels/AddModeratorToChannel
* Csatlakoztak a csatornádhoz
  * in: channels/CreateChannelJoinCosmosTrigger
* Elvették a moderátorjogod a csatornából
  * in: channels/RemoveModeratorFromChannel
* Kommenteltek a posztod alá
  * in: comments/CreateCommentCosmosTrigger
* Szavazatot kapott a kommented
  * in: comments/VoteCommentCosmosTrigger
* Új poszt készült a csatornában, amihez csatlakozva/moderátor/tulajdonos vagy
  * in: posts/CreatePostCosmosTrigger
* Szavazatot kapott a posztod
  * in: posts/VotePostCosmosTrigger

Események, amikre még nincs notification készítés:
* Törölték a csatornát, amelynek tagja voltál
* Megváltozott a csatorna uriName-je, aminek tagja vagy
* Törölték a posztodat (rakjuk bele a DeletePostnál az attribútumokba, ki törölte, és a DeletePostCosmosTriggerben pedig kiszedjük)
* Törölték a kommentedet (ki törölte, same as above)
* Vote-ok aggregálva posztokra ("A posztod elért 10 upvote-ot stb.")
* Vote-ok aggregálva kommentekre ("A kommented elért 10 upvote-ot stb.")
